### ISSUE TITLE
RHEL-07-010490 Error

### ISSUE THREAD

**Issue by riteshapatel** [MindPointGroup/RHEL7-STIG#21]
Hi,

So trying to apply RHEL-7 STIGs, execution stops @ RHEL-07-010490 with following error. Any thoughts? 

```
The full traceback is:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 89, in run
    items = self._get_loop_items()
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 202, in _get_loop_items
    loop_terms = listify_lookup_plugin_terms(terms=self._task.loop_args, templar=templar, loader=self._loader, fail_on_undefined=True, convert_bare=False)
  File "/Library/Python/2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/Library/Python/2.7/site-packages/ansible/template/__init__.py", line 437, in template
    disable_lookups=disable_lookups,
  File "/Library/Python/2.7/site-packages/ansible/template/__init__.py", line 659, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/Library/Python/2.7/site-packages/ansible/template/__init__.py", line 202, in resolve_or_missing
    val = super(AnsibleContext, self).resolve_or_missing(key)
  File "/Library/Python/2.7/site-packages/jinja2/runtime.py", line 216, in resolve_or_missing
    return resolve_or_missing(self, key)
  File "/Library/Python/2.7/site-packages/jinja2/runtime.py", line 128, in resolve_or_missing
    return context.parent[key]
  File "/Library/Python/2.7/site-packages/ansible/template/vars.py", line 95, in __getitem__
    raise type(e)(to_native(variable) + ': ' + e.message)
NameError: [{u'regexp': u'^set superusers', u'line': u'set superusers="root"'}, {u'regexp': u'^password_pbkdf2 root', u'line': u"password_pbkdf2 root {{ rhel7stig_bootloader_password | grub2_hash(salt='KeokpkECTJeoDhEA5XtiLQ') }}"}]: global name 'errors' is not defined

fatal: [34.229.162.171]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

```

Below are ansible / python versions on the controller m/c.

```
ansible 2.3.1.0
python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

Thx,

Ritesh

**Comment by shepdelacreme** [comment]
@riteshapatel In order to fix your immediate issue you need to have the `passlib` python module installed on macOS machines for the `grub2_hash` filter plugin to work. 

That said there is a bug in the plugin because it shouldn't be throwing a full traceback when you don't have it installed.
